paths:
  /api/products:
    get:
      summary: Devuelve los productos registrados hasta el momento
      tags:
        - Products
      responses:
        "200":
          description: Los productos se obtienen correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno, en este endpoint se deberá a un error en la base de datos, revisar conexión o parámetros de búsqueda
    post:
      summary: crea un nuevo producto
      tags:
        - Products

  /api/products/{pid}:
    get:
      summary: Obtiene el producto del id proporcionado
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: id para obtener el producto
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado correctamente
        "404":
          description: Producto no encontrado
    put:
      summary: Actualiza el producto del id proporcionado
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: id para obtener al producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/UpdateProduct"
      responses:
        "200":
          description: Producto modificado
        "400":
          description: Datos incompletos, corroborar cuerpo
        "500":
          description: Error interno
    delete:
      summary: Elimina al producto del id proporcionado
      tags:
        - Products

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Titulo del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: string
          description: Código del producto (único)
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Status del producto
        stock: 
          type: number
          description: Stock del producto
        category: 
          type: string
          description: Categoría del producto
        thumbnail: 
          type: array
          description: Imagen del producto
        owner:
          type: string
          description: Rol del creador del producto
        _id: 
          type: string
          description: Id autogenerado por mongoDB
      example:
        _id": ObjectId("646bb56fa0e9f197f4e8f59c")
        title: Shampoo
        description: limpieza
        code: abc1
        price: 150
        status: true
        stock: 0
        category: Higiene
        thumbnail: []
        owner: admin
  
  requestBodies:
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: Nuevo título del producto
        description:
          type: string
          description: Nueva descripción del producto
        price:
          type: number
          description: Nuevo precio del producto
        stock:
          type: number
          description: Nuevo stock del producto